// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: jobrpc/jobsvc.proto

package jobrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobStatusResponse_Status int32

const (
	GetJobStatusResponse_UNKNOWN  GetJobStatusResponse_Status = 0
	GetJobStatusResponse_RUNNING  GetJobStatusResponse_Status = 1 // job is active
	GetJobStatusResponse_FINISHED GetJobStatusResponse_Status = 2 // job finished successfully
	GetJobStatusResponse_FAILED   GetJobStatusResponse_Status = 3 // job finished with non-zero exit code
	GetJobStatusResponse_STOPPED  GetJobStatusResponse_Status = 4 // job was manually stopped
	GetJobStatusResponse_ERROR    GetJobStatusResponse_Status = 5 // job creation failed
)

// Enum value maps for GetJobStatusResponse_Status.
var (
	GetJobStatusResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
		2: "FINISHED",
		3: "FAILED",
		4: "STOPPED",
		5: "ERROR",
	}
	GetJobStatusResponse_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"RUNNING":  1,
		"FINISHED": 2,
		"FAILED":   3,
		"STOPPED":  4,
		"ERROR":    5,
	}
)

func (x GetJobStatusResponse_Status) Enum() *GetJobStatusResponse_Status {
	p := new(GetJobStatusResponse_Status)
	*p = x
	return p
}

func (x GetJobStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJobStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_jobrpc_jobsvc_proto_enumTypes[0].Descriptor()
}

func (GetJobStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_jobrpc_jobsvc_proto_enumTypes[0]
}

func (x GetJobStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJobStatusResponse_Status.Descriptor instead.
func (GetJobStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{5, 0}
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{0}
}

func (x *StartJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartJobRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{1}
}

func (x *StartJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{2}
}

func (x *StopJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResponse) Reset() {
	*x = StopJobResponse{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResponse) ProtoMessage() {}

func (x *StopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResponse.ProtoReflect.Descriptor instead.
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{3}
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        GetJobStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=jobrpc.GetJobStatusResponse_Status" json:"status,omitempty"`
	Command       string                      `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      int32                       `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobStatusResponse) GetStatus() GetJobStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetJobStatusResponse_UNKNOWN
}

func (x *GetJobStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetJobStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type GetJobLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsRequest) Reset() {
	*x = GetJobLogsRequest{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsRequest) ProtoMessage() {}

func (x *GetJobLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsRequest.ProtoReflect.Descriptor instead.
func (*GetJobLogsRequest) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsResponse) Reset() {
	*x = GetJobLogsResponse{}
	mi := &file_jobrpc_jobsvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsResponse) ProtoMessage() {}

func (x *GetJobLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobrpc_jobsvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsResponse.ProtoReflect.Descriptor instead.
func (*GetJobLogsResponse) Descriptor() ([]byte, []int) {
	return file_jobrpc_jobsvc_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobLogsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jobrpc_jobsvc_proto protoreflect.FileDescriptor

const file_jobrpc_jobsvc_proto_rawDesc = "" +
	"\n" +
	"\x13jobrpc/jobsvc.proto\x12\x06jobrpc\"?\n" +
	"\x0fStartJobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\"\n" +
	"\x10StartJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eStopJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fStopJobResponse\"%\n" +
	"\x13GetJobStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe0\x01\n" +
	"\x14GetJobStatusResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.jobrpc.GetJobStatusResponse.StatusR\x06status\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"T\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aSTOPPED\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x05\"#\n" +
	"\x11GetJobLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x12GetJobLogsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x99\x02\n" +
	"\n" +
	"JobService\x12=\n" +
	"\bStartJob\x12\x17.jobrpc.StartJobRequest\x1a\x18.jobrpc.StartJobResponse\x12:\n" +
	"\aStopJob\x12\x16.jobrpc.StopJobRequest\x1a\x17.jobrpc.StopJobResponse\x12I\n" +
	"\fGetJobStatus\x12\x1b.jobrpc.GetJobStatusRequest\x1a\x1c.jobrpc.GetJobStatusResponse\x12E\n" +
	"\n" +
	"GetJobLogs\x12\x19.jobrpc.GetJobLogsRequest\x1a\x1a.jobrpc.GetJobLogsResponse0\x01B\"Z github.com/wrboyce/jobsvc/jobrpcb\x06proto3"

var (
	file_jobrpc_jobsvc_proto_rawDescOnce sync.Once
	file_jobrpc_jobsvc_proto_rawDescData []byte
)

func file_jobrpc_jobsvc_proto_rawDescGZIP() []byte {
	file_jobrpc_jobsvc_proto_rawDescOnce.Do(func() {
		file_jobrpc_jobsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobrpc_jobsvc_proto_rawDesc), len(file_jobrpc_jobsvc_proto_rawDesc)))
	})
	return file_jobrpc_jobsvc_proto_rawDescData
}

var file_jobrpc_jobsvc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobrpc_jobsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jobrpc_jobsvc_proto_goTypes = []any{
	(GetJobStatusResponse_Status)(0), // 0: jobrpc.GetJobStatusResponse.Status
	(*StartJobRequest)(nil),          // 1: jobrpc.StartJobRequest
	(*StartJobResponse)(nil),         // 2: jobrpc.StartJobResponse
	(*StopJobRequest)(nil),           // 3: jobrpc.StopJobRequest
	(*StopJobResponse)(nil),          // 4: jobrpc.StopJobResponse
	(*GetJobStatusRequest)(nil),      // 5: jobrpc.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),     // 6: jobrpc.GetJobStatusResponse
	(*GetJobLogsRequest)(nil),        // 7: jobrpc.GetJobLogsRequest
	(*GetJobLogsResponse)(nil),       // 8: jobrpc.GetJobLogsResponse
}
var file_jobrpc_jobsvc_proto_depIdxs = []int32{
	0, // 0: jobrpc.GetJobStatusResponse.status:type_name -> jobrpc.GetJobStatusResponse.Status
	1, // 1: jobrpc.JobService.StartJob:input_type -> jobrpc.StartJobRequest
	3, // 2: jobrpc.JobService.StopJob:input_type -> jobrpc.StopJobRequest
	5, // 3: jobrpc.JobService.GetJobStatus:input_type -> jobrpc.GetJobStatusRequest
	7, // 4: jobrpc.JobService.GetJobLogs:input_type -> jobrpc.GetJobLogsRequest
	2, // 5: jobrpc.JobService.StartJob:output_type -> jobrpc.StartJobResponse
	4, // 6: jobrpc.JobService.StopJob:output_type -> jobrpc.StopJobResponse
	6, // 7: jobrpc.JobService.GetJobStatus:output_type -> jobrpc.GetJobStatusResponse
	8, // 8: jobrpc.JobService.GetJobLogs:output_type -> jobrpc.GetJobLogsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jobrpc_jobsvc_proto_init() }
func file_jobrpc_jobsvc_proto_init() {
	if File_jobrpc_jobsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobrpc_jobsvc_proto_rawDesc), len(file_jobrpc_jobsvc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobrpc_jobsvc_proto_goTypes,
		DependencyIndexes: file_jobrpc_jobsvc_proto_depIdxs,
		EnumInfos:         file_jobrpc_jobsvc_proto_enumTypes,
		MessageInfos:      file_jobrpc_jobsvc_proto_msgTypes,
	}.Build()
	File_jobrpc_jobsvc_proto = out.File
	file_jobrpc_jobsvc_proto_goTypes = nil
	file_jobrpc_jobsvc_proto_depIdxs = nil
}
